// Code generated by MockGen. DO NOT EDIT.
// Source: internal/models/secret_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/melkomukovki/LockBox/internal/models"
)

// MockISecretRepository is a mock of SecretRepository interface.
type MockISecretRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISecretRepositoryMockRecorder
}

// MockISecretRepositoryMockRecorder is the mock recorder for MockISecretRepository.
type MockISecretRepositoryMockRecorder struct {
	mock *MockISecretRepository
}

// NewMockISecretRepository creates a new mock instance.
func NewMockISecretRepository(ctrl *gomock.Controller) *MockISecretRepository {
	mock := &MockISecretRepository{ctrl: ctrl}
	mock.recorder = &MockISecretRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISecretRepository) EXPECT() *MockISecretRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockISecretRepository) Create(ctx context.Context, secret *models.Secret) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, secret)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockISecretRepositoryMockRecorder) Create(ctx, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockISecretRepository)(nil).Create), ctx, secret)
}

// Delete mocks base method.
func (m *MockISecretRepository) Delete(ctx context.Context, secretId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, secretId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockISecretRepositoryMockRecorder) Delete(ctx, secretId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockISecretRepository)(nil).Delete), ctx, secretId)
}

// Get mocks base method.
func (m *MockISecretRepository) Get(ctx context.Context, secretId int) (*models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, secretId)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockISecretRepositoryMockRecorder) Get(ctx, secretId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockISecretRepository)(nil).Get), ctx, secretId)
}

// GetByUserId mocks base method.
func (m *MockISecretRepository) GetByUserId(ctx context.Context, userId int) ([]models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", ctx, userId)
	ret0, _ := ret[0].([]models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockISecretRepositoryMockRecorder) GetByUserId(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockISecretRepository)(nil).GetByUserId), ctx, userId)
}

// Update mocks base method.
func (m *MockISecretRepository) Update(ctx context.Context, secret *models.Secret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockISecretRepositoryMockRecorder) Update(ctx, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockISecretRepository)(nil).Update), ctx, secret)
}
