# Пример конфигурации сервиса

server:
  host: "0.0.0.0" # Адрес на котором будет запущен сервер
  port: 8888      # Порт, который будет слушать сервер
database:
  host: "localhost"   # Адрес сервера БД
  port: 5432          # Порт БД
  username: "admin"   # Имя пользователя для подключения к БД
  password: "admin"   # Пароль пользователя для подключения к БД
  database: "lockbox" # Название БД
auth:
  access_token_ttl: "24h"       # Срок жизни access token
  signing_key: "test_auth_key"  # Ключ, который используется для создания подписи JWT токена
log:
  level: "debug"  # Уровень логирования